### ISSUE TITLE
老哥可以出一个自动签到的吗

### ISSUE THREAD

**Issue by qfcxhh** [Chorer/YiFuDaoChecker#2]
老哥想要一个自动签到的

**Comment by Chorer** [comment]
> 老哥想要一个自动签到的

我们学校没有签到的要求，抓不到接口地址。你会抓包的话可以提供一下相关信息给我。

**Comment by qfcxhh** [comment]
我加你tg上说吧

**Comment by Chorer** [comment]
> 我加你tg上说吧

QQ 聊吧

**Comment by qfcxhh** [comment]
QQ多少呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 晚上8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chorer/YiFuDaoChecker-cloudFunction] 老哥可以出一个自动签到的吗 (Issue #2)





  
我加你tg上说吧
  
QQ 聊吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chorer** [comment]
> QQ多少呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月7日(星期五) 晚上8:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Chorer/YiFuDaoChecker-cloudFunction] 老哥可以出一个自动签到的吗 (Issue #2) 我加你tg上说吧 QQ 聊吧 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

1581209025

**Comment by 2104050124** [comment]
![屏幕截图 2022-05-02 000219](https://user-images.githubusercontent.com/102683682/166154149-f6cef3eb-8b77-48c3-a483-418108388d36.png)
为什么会这样啊？

**Comment by Chorer** [comment]
> ![屏幕截图 2022-05-02 000219](https://user-images.githubusercontent.com/102683682/166154149-f6cef3eb-8b77-48c3-a483-418108388d36.png) 为什么会这样啊？

请另外开一个issue。不要在此issue下讨论不相关问题。
